import './contractCreateEditModalActions';
import './contractCreateEditTabs';
import './contractCreateEditTabs.less';
import './detailsTab/contractCreateEditModalHead';
import './detailsTab/contractCreateEditModalDetails';
import './detailsTab/contractCreateEditModalAside';
import './detailsTab/contractEditDetailsTab';
import './historyTab/contractEditHistoryTab';
import './historyTab/contractEditHistoryTab.less'
